plugin:
    name: 'brutalhost.passwordless::lang.plugin.name'
    description: 'brutalhost.passwordless::lang.plugin.description'
    author: 'noc.io'
    icon: wn-icon-key
    homepage: 'https://github.com/helmutkaufmann/wn-passwordless-plugin'
