plugin:
    name: 'mercator.passwordless::lang.plugin.name'
    description: 'mercator.passwordless::lang.plugin.description'
    author: 'noc.io'
    icon: wn-icon-key
    homepage: 'https://github.com/helmutkaufmann/wn-passwordless-plugin'
