plugin:
    name: 'nocio.passwordless::lang.plugin.name'
    description: 'nocio.passwordless::lang.plugin.description'
    author: 'noc.io'
    icon: oc-icon-key
    homepage: 'https://github.com/nocio/oc-passwordless-plugin'
